name: Build shared

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@master
      name: checkout

    - run: ./build_shared.bat
      name: build

    - uses: actions/upload-artifact@master
      with:
        name: OpenSSL Build
        path: C:\OpenSSL-1.0.2u-XP.7z
      name: upload-openssl-build
