name: Build static

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@master
      name: checkout

    - run: ./build_static.bat
      name: build

    - uses: actions/upload-artifact@master
      with:
        name: OpenSSL Build
        path: C:\OpenSSL-1.0.2u-Static-XP.7z
      name: upload-openssl-build
